name: funcex1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_Deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          3.1.x
          5.0.x
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore  --configuration Release
    
    - name: Archive Action
      uses: thedoctor0/zip-release@master
      with:
          type: 'zip'
          path: '/home/runner/work/AzureFunctionExercise1/AzureFunctionExercise1/bin/Release/net5.0/'
          directory: '/home/runner/work/AzureFunctionExercise1/AzureFunctionExercise1/bin/Release/net5.0/'
          filename: 'funcex1-release.zip'
    
    - name: Azure Blob Storage Upload
      uses: LanceMcCarthy/Action-AzureBlobUpload@v1.10.0
      with:
        # The connection string for the storage account
          connection_string: ${{ secrets.ConnectionString }}
        # The name of the storage account container these assets will be uploaded to
          container_name: functioncodepackages
        # The name of the directory you want to upload
          source_folder: '/home/runner/work/AzureFunctionExercise1/AzureFunctionExercise1/bin/Release/net5.0/funcex1-release.zip'
          fail_if_source_empty: true
          is_recursive: false
        
       
