name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release
  archive:
     needs: build
     runs-on: ubuntu-latest
     name: Archive Action
     steps:
     - name: action-build-zip
        # You may pin to the exact commit or the version.
        # uses: byteever/action-build-zip@23d77e1778849e35de1b4e9dbb16d4b64a4714e6
       uses: byteever/action-build-zip@1
       with:
          # See byteever/action-zip README.md for more info
          filename: 'funcex1-release.zip'
  publish:
      needs: archive
      runs-on: ubuntu-latest
      steps:
      - name: Azure Blob Storage Upload
          # You may pin to the exact commit or the version.
          # uses: bacongobbler/azure-blob-storage-upload@779a18b594a1a7cf5412645e06c856324a8b01e5
        uses: bacongobbler/azure-blob-storage-upload@v1.1.1
        with:
        # The connection string for the storage account
          connection_string: $({ secrest.ConnenctionString })
        # The name of the storage account container these assets will be uploaded to
          container_name: functioncodepackages
        # The name of the directory you want to upload
          source_dir: ./funcex1-release.zip
        # Extra arguments that can be passed to `az storage blob upload-batch|sync`. Useful for passing flags like `--pattern` or `--destination-path`
        #  extra_args: # optional
        # Use `az storage blob sync` to synchronize blobs recursively
          sync: false # optional
